basePath: /api/v1
definitions:
  models.CashEntry:
    properties:
      amount:
        type: number
      createdAt:
        type: string
      customer:
        $ref: '#/definitions/models.Customer'
      customerID:
        type: integer
      description:
        type: string
      entryType:
        description: e.g., income, expense
        type: string
      id:
        type: integer
      shop:
        $ref: '#/definitions/models.Shop'
      shopID:
        type: integer
      updatedAt:
        type: string
      user:
        $ref: '#/definitions/models.User'
      userID:
        type: integer
    type: object
  models.Customer:
    properties:
      address:
        type: string
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
      shop:
        $ref: '#/definitions/models.Shop'
      shopID:
        type: integer
      updatedAt:
        type: string
      userID:
        type: integer
    type: object
  models.CustomerTransaction:
    properties:
      amount:
        type: number
      createdAt:
        type: string
      customer:
        $ref: '#/definitions/models.Customer'
      customerID:
        type: integer
      description:
        type: string
      id:
        type: integer
      shop:
        $ref: '#/definitions/models.Shop'
      shopID:
        type: integer
      transactionType:
        description: e.g., credit, debit
        type: string
      updatedAt:
        type: string
      user:
        $ref: '#/definitions/models.User'
      userID:
        type: integer
    type: object
  models.Employee:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      role:
        description: e.g. employee, manager
        type: string
      shop:
        $ref: '#/definitions/models.Shop'
      shopID:
        type: integer
      updatedAt:
        type: string
      user:
        $ref: '#/definitions/models.User'
      userID:
        type: integer
    type: object
  models.EmployeeRoleUpdate:
    properties:
      role:
        type: string
    type: object
  models.LoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.PasswordUpdateReq:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    type: object
  models.Shop:
    properties:
      address:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      owner:
        $ref: '#/definitions/models.User'
      ownerID:
        type: integer
      updatedAt:
        type: string
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      role:
        description: e.g., admin, owner, employee etc.
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: esezer@egetechno.com
    name: API SUPPORT
    url: http://www.swagger.io/support
  description: finance app for tradesman
  license:
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Defterdar-go
  version: "1.0"
paths:
  /cash:
    get:
      consumes:
      - application/json
      description: Get cash entries with dates
      parameters:
      - description: CashEntry
        in: body
        name: cashentry
        required: true
        schema:
          $ref: '#/definitions/models.CashEntry'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CashEntry'
        "400":
          description: Invalid input.
          schema:
            type: string
        "404":
          description: Shop not found.
          schema:
            type: string
        "500":
          description: Failed to get cash entries.
          schema:
            type: string
      summary: Get cash entries
      tags:
      - Cash
    post:
      consumes:
      - application/json
      description: Create a cash entry with description, amount, type, and optionally
        link it to a customer
      parameters:
      - description: CashEntry
        in: body
        name: cashentry
        required: true
        schema:
          $ref: '#/definitions/models.CashEntry'
      produces:
      - application/json
      responses:
        "201":
          description: Cash entry created successfully.
          schema:
            type: string
        "400":
          description: Invalid input.
          schema:
            type: string
        "404":
          description: Shop or customer not found.
          schema:
            type: string
        "500":
          description: Failed to create cash entry.
          schema:
            type: string
      summary: Create a cash entry
      tags:
      - Cash
  /employee/{shop_id}:
    delete:
      consumes:
      - application/json
      description: Remove an employee from shop
      parameters:
      - description: Employee
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: Employee removed successfully.
          schema:
            type: string
        "400":
          description: The employee is not an employee of this workplace.
          schema:
            type: string
        "401":
          description: Unauthorized.
          schema:
            type: string
        "404":
          description: Employee not found.
          schema:
            type: string
        "500":
          description: Failed to remove employee.
          schema:
            type: string
      summary: Remove an employee
      tags:
      - Employee
    get:
      consumes:
      - application/json
      description: List employees in shop
      parameters:
      - description: Employee
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Employee'
        "400":
          description: Invalid id.
          schema:
            type: string
        "401":
          description: Unauthorized.
          schema:
            type: string
        "404":
          description: Employees not found.
          schema:
            type: string
      summary: List employees
      tags:
      - Employee
    post:
      consumes:
      - application/json
      description: Add an employee with role
      parameters:
      - description: Employee
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: Employee added successfully.
          schema:
            type: string
        "400":
          description: Invalid input.
          schema:
            type: string
        "401":
          description: Unauthorized.
          schema:
            type: string
        "404":
          description: Shop not found.
          schema:
            type: string
        "500":
          description: Failed to add employee.
          schema:
            type: string
      summary: Add an employee
      tags:
      - Employee
  /employee/{user_id}:
    put:
      consumes:
      - application/json
      description: Update an employee with role
      parameters:
      - description: Employee
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/models.EmployeeRoleUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: Employee role updated successfully.
          schema:
            type: string
        "400":
          description: Invalid input.
          schema:
            type: string
        "401":
          description: Unauthorized.
          schema:
            type: string
        "404":
          description: Employee not found.
          schema:
            type: string
        "500":
          description: Failed to update employee.
          schema:
            type: string
      summary: Update an employee
      tags:
      - Employee
  /shop:
    post:
      consumes:
      - application/json
      description: Create a shop with name and adress
      parameters:
      - description: Shop
        in: body
        name: shop
        required: true
        schema:
          $ref: '#/definitions/models.Shop'
      produces:
      - application/json
      responses:
        "200":
          description: Shop created successfully.
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Failed to create shop.
          schema:
            type: string
      summary: Create a shop
      tags:
      - Shop
  /shop/{shop_id}:
    delete:
      consumes:
      - application/json
      description: Delete a shop
      parameters:
      - description: Shop
        in: body
        name: shop
        required: true
        schema:
          $ref: '#/definitions/models.Shop'
      produces:
      - application/json
      responses:
        "200":
          description: Shop deleted successfully.
          schema:
            type: string
        "400":
          description: Invalid id.
          schema:
            type: string
        "401":
          description: Unauthorized.
          schema:
            type: string
        "404":
          description: Shop not found.
          schema:
            type: string
        "500":
          description: Failed to delete shop.
          schema:
            type: string
      summary: Delete a shop
      tags:
      - Shop
    put:
      consumes:
      - application/json
      description: Update shop's name and adress
      parameters:
      - description: Shop
        in: body
        name: shop
        required: true
        schema:
          $ref: '#/definitions/models.Shop'
      produces:
      - application/json
      responses:
        "200":
          description: Shop updated successfully.
          schema:
            type: string
        "400":
          description: Invalid input.
          schema:
            type: string
        "401":
          description: Unauthorized.
          schema:
            type: string
        "500":
          description: Failed to update shop.
          schema:
            type: string
      summary: Update shop
      tags:
      - Shop
  /transaction:
    post:
      consumes:
      - application/json
      description: Create a new transaction.
      parameters:
      - description: Transaction
        in: body
        name: Transaction
        required: true
        schema:
          $ref: '#/definitions/models.CustomerTransaction'
      produces:
      - application/json
      responses:
        "201":
          description: Transaction created successfully.
          schema:
            type: string
        "400":
          description: Invalid input.
          schema:
            type: string
        "500":
          description: Failed to create transaction
          schema:
            type: string
      summary: Create a transaction
      tags:
      - Transaction
  /transaction/{transaction_id}:
    get:
      consumes:
      - application/json
      description: Get a transaction.
      parameters:
      - description: Transaction
        in: body
        name: Transaction
        required: true
        schema:
          $ref: '#/definitions/models.CustomerTransaction'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CustomerTransaction'
        "400":
          description: Failed to create transaction
          schema:
            type: string
        "404":
          description: Failed to get transaction.
          schema:
            type: string
      summary: Get a transaction
      tags:
      - Transaction
  /user/get-profile:
    get:
      consumes:
      - application/json
      description: Pulls the user's own profile information.
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Invalid input.
          schema:
            type: string
        "404":
          description: User not found.
          schema:
            type: string
      summary: GetProfile a user
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/json
      description: Register a new user with name, email, password, role
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.LoginReq'
      produces:
      - application/json
      responses:
        "201":
          description: 'token: '
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Login a new user
      tags:
      - Auth
  /user/register:
    post:
      consumes:
      - application/json
      description: Register a new user with name, email, password, role (e.g. owner,
        employee)
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully.
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Register a new user
      tags:
      - Auth
  /user/update-password:
    put:
      consumes:
      - application/json
      description: Update the user's password.
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.PasswordUpdateReq'
      produces:
      - application/json
      responses:
        "201":
          description: Password updated successfully.
          schema:
            type: string
        "400":
          description: Invalid input.
          schema:
            type: string
        "404":
          description: User not found.
          schema:
            type: string
      summary: UpdatePassword a user
      tags:
      - User
  /user/update-profile:
    put:
      consumes:
      - application/json
      description: Update the user's profile.
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: User updated successfully.
          schema:
            type: string
        "400":
          description: Invalid input.
          schema:
            type: string
        "404":
          description: User not found.
          schema:
            type: string
      summary: UpdateProfile a user
      tags:
      - User
  /users/{user_id}/delete:
    delete:
      description: Delete a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: User deleted successfully
          schema:
            type: string
        "400":
          description: Invalid user ID
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
      summary: Delete a user
      tags:
      - User
  /users/close-account:
    delete:
      description: Close account
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Account closed successfully.
          schema:
            type: string
        "400":
          description: Invalid user ID
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
      summary: Close a user own account
      tags:
      - User
swagger: "2.0"
