basePath: /api/v1
definitions:
  models.LoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      role:
        description: e.g., admin, user, etc.
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: esezer@egetechno.com
    name: API SUPPORT
    url: http://www.swagger.io/support
  description: finance app for tradesman
  license:
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Defterdar-go
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: Register a new user with name, email, password, role
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.LoginReq'
      produces:
      - application/json
      responses:
        "201":
          description: 'token: '
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Login a new user
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: Register a new user with name, email, password, role
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully.
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Register a new user
      tags:
      - User
swagger: "2.0"
